---
asyncapi: 3.0.0
info:
  title: API Document for REST APIs
  version: 1.0.0
  license:
    name: Aklivity Community License
    url: https://github.com/aklivity/zillabase/blob/develop/LICENSE
servers:
  http:
    host: localhost:8080
    protocol: http
channels:
  petstore_customers-stream-identity:
    address: "/petstore_customers-stream-identity"
    messages:
      PETSTORE_CUSTOMERSMessage:
        "$ref": "#/components/messages/PETSTORE_CUSTOMERSMessage"
  petstore_verified_customers:
    address: "/petstore_verified_customers"
    messages:
      PETSTORE_VERIFIED_CUSTOMERSMessages:
        "$ref": "#/components/messages/PETSTORE_VERIFIED_CUSTOMERSMessages"
      PETSTORE_VERIFIED_CUSTOMERSMessage:
        "$ref": "#/components/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
  petstore_pets-item:
    address: "/petstore_pets/{id}"
    parameters:
      id:
        description: Id of the item.
    messages:
      PETSTORE_PETSMessage:
        "$ref": "#/components/messages/PETSTORE_PETSMessage"
  petstore_verified_customers-item:
    address: "/petstore_verified_customers/{id}"
    parameters:
      id:
        description: Id of the item.
    messages:
      PETSTORE_VERIFIED_CUSTOMERSMessage:
        "$ref": "#/components/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
  petstore_pets-stream:
    address: "/petstore_pets-stream"
    messages:
      PETSTORE_PETSMessage:
        "$ref": "#/components/messages/PETSTORE_PETSMessage"
  petstore_customers-stream:
    address: "/petstore_customers-stream"
    messages:
      PETSTORE_CUSTOMERSMessage:
        "$ref": "#/components/messages/PETSTORE_CUSTOMERSMessage"
  petstore_verified_customers-stream:
    address: "/petstore_verified_customers-stream"
    messages:
      PETSTORE_VERIFIED_CUSTOMERSMessage:
        "$ref": "#/components/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
  petstore_customers-item:
    address: "/petstore_customers/{id}"
    parameters:
      id:
        description: Id of the item.
    messages:
      PETSTORE_CUSTOMERSMessage:
        "$ref": "#/components/messages/PETSTORE_CUSTOMERSMessage"
  petstore_pets:
    address: "/petstore_pets"
    messages:
      PETSTORE_PETSMessage:
        "$ref": "#/components/messages/PETSTORE_PETSMessage"
      PETSTORE_PETSMessages:
        "$ref": "#/components/messages/PETSTORE_PETSMessages"
  petstore_verified_customers-stream-identity:
    address: "/petstore_verified_customers-stream-identity"
    messages:
      PETSTORE_VERIFIED_CUSTOMERSMessage:
        "$ref": "#/components/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
  petstore_pets-stream-identity:
    address: "/petstore_pets-stream-identity"
    messages:
      PETSTORE_PETSMessage:
        "$ref": "#/components/messages/PETSTORE_PETSMessage"
  petstore_customers:
    address: "/petstore_customers"
    messages:
      PETSTORE_CUSTOMERSMessages:
        "$ref": "#/components/messages/PETSTORE_CUSTOMERSMessages"
      PETSTORE_CUSTOMERSMessage:
        "$ref": "#/components/messages/PETSTORE_CUSTOMERSMessage"
operations:
  doPETSTORE_CUSTOMERSCreate:
    action: send
    channel:
      "$ref": "#/channels/petstore_customers"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: POST
    messages:
    - "$ref": "#/channels/petstore_customers/messages/PETSTORE_CUSTOMERSMessage"
  doPETSTORE_VERIFIED_CUSTOMERSCreate:
    action: send
    channel:
      "$ref": "#/channels/petstore_verified_customers"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: POST
    messages:
    - "$ref": "#/channels/petstore_verified_customers/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
  doPETSTORE_PETSCreate:
    action: send
    channel:
      "$ref": "#/channels/petstore_pets"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: POST
    messages:
    - "$ref": "#/channels/petstore_pets/messages/PETSTORE_PETSMessage"
  onPETSTORE_CUSTOMERSGet:
    action: receive
    channel:
      "$ref": "#/channels/petstore_customers"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: GET
    messages:
    - "$ref": "#/channels/petstore_customers/messages/PETSTORE_CUSTOMERSMessages"
  onPETSTORE_PETSGetItem:
    action: receive
    channel:
      "$ref": "#/channels/petstore_pets-item"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: GET
    messages:
    - "$ref": "#/channels/petstore_pets-item/messages/PETSTORE_PETSMessage"
  onPETSTORE_VERIFIED_CUSTOMERSGetItem:
    action: receive
    channel:
      "$ref": "#/channels/petstore_verified_customers-item"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: GET
    messages:
    - "$ref": "#/channels/petstore_verified_customers-item/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
  onPETSTORE_CUSTOMERSGetItem:
    action: receive
    channel:
      "$ref": "#/channels/petstore_customers-item"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: GET
    messages:
    - "$ref": "#/channels/petstore_customers-item/messages/PETSTORE_CUSTOMERSMessage"
  onPETSTORE_PETSReadItem:
    action: receive
    channel:
      "$ref": "#/channels/petstore_pets-stream-identity"
    bindings:
      x-zilla-sse-kafka:
        filters:
        - {}
      x-zilla-sse: {}
    messages:
    - "$ref": "#/channels/petstore_pets-stream-identity/messages/PETSTORE_PETSMessage"
  doPETSTORE_PETSUpdate:
    action: send
    channel:
      "$ref": "#/channels/petstore_pets-item"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: PUT
    messages:
    - "$ref": "#/channels/petstore_pets-item/messages/PETSTORE_PETSMessage"
  onPETSTORE_PETSGet:
    action: receive
    channel:
      "$ref": "#/channels/petstore_pets"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: GET
    messages:
    - "$ref": "#/channels/petstore_pets/messages/PETSTORE_PETSMessages"
  onPETSTORE_CUSTOMERSRead:
    action: receive
    channel:
      "$ref": "#/channels/petstore_customers-stream"
    bindings:
      x-zilla-sse: {}
    messages:
    - "$ref": "#/channels/petstore_customers-stream/messages/PETSTORE_CUSTOMERSMessage"
  onPETSTORE_PETSRead:
    action: receive
    channel:
      "$ref": "#/channels/petstore_pets-stream"
    bindings:
      x-zilla-sse: {}
    messages:
    - "$ref": "#/channels/petstore_pets-stream/messages/PETSTORE_PETSMessage"
  onPETSTORE_VERIFIED_CUSTOMERSRead:
    action: receive
    channel:
      "$ref": "#/channels/petstore_verified_customers-stream"
    bindings:
      x-zilla-sse: {}
    messages:
    - "$ref": "#/channels/petstore_verified_customers-stream/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
  doPETSTORE_CUSTOMERSUpdate:
    action: send
    channel:
      "$ref": "#/channels/petstore_customers-item"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: PUT
    messages:
    - "$ref": "#/channels/petstore_customers-item/messages/PETSTORE_CUSTOMERSMessage"
  onPETSTORE_VERIFIED_CUSTOMERSGet:
    action: receive
    channel:
      "$ref": "#/channels/petstore_verified_customers"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: GET
    messages:
    - "$ref": "#/channels/petstore_verified_customers/messages/PETSTORE_VERIFIED_CUSTOMERSMessages"
  doPETSTORE_VERIFIED_CUSTOMERSUpdate:
    action: send
    channel:
      "$ref": "#/channels/petstore_verified_customers-item"
    bindings:
      http:
        bindingVersion: 0.3.0
        method: PUT
    messages:
    - "$ref": "#/channels/petstore_verified_customers-item/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
  onPETSTORE_CUSTOMERSReadItem:
    action: receive
    channel:
      "$ref": "#/channels/petstore_customers-stream-identity"
    bindings:
      x-zilla-sse-kafka:
        filters:
        - {}
      x-zilla-sse: {}
    messages:
    - "$ref": "#/channels/petstore_customers-stream-identity/messages/PETSTORE_CUSTOMERSMessage"
  onPETSTORE_VERIFIED_CUSTOMERSReadItem:
    action: receive
    channel:
      "$ref": "#/channels/petstore_verified_customers-stream-identity"
    bindings:
      x-zilla-sse-kafka:
        filters:
        - {}
      x-zilla-sse: {}
    messages:
    - "$ref": "#/channels/petstore_verified_customers-stream-identity/messages/PETSTORE_VERIFIED_CUSTOMERSMessage"
components:
  schemas:
    public.petstore_verified_customers-value:
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      schema:
        fields:
        - name: id
          type:
          - 'null'
          - type: string
        - name: points
          type:
          - 'null'
          - type: string
        name: petstore_verified_customers
        namespace: public
        type: record
    public.petstore_verified_customers-values:
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      schema:
        type: array
        items:
          fields:
            - name: name
              type:
                - 'null'
                - type: string
            - name: status
              type:
                - 'null'
                - type: string
          name: petstore_customers
          namespace: public
          type: record
      namespace: dev
    public.petstore_customers-value:
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      schema:
        fields:
        - name: name
          type:
          - 'null'
          - type: string
        - name: status
          type:
          - 'null'
          - type: string
        name: petstore_customers
        namespace: public
        type: record
    public.petstore_customers-values:
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      schema:
        type: array
        items:
          fields:
            - name: id
              type:
                - 'null'
                - type: string
            - name: breed
              type:
                - 'null'
                - type: string
          name: petstore_pets
          namespace: public
          type: record
    public.petstore_pets-value:
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      schema:
        fields:
          - name: id
            type:
              - 'null'
              - type: string
          - name: breed
            type:
              - 'null'
              - type: string
        name: petstore_pets
        namespace: public
        type: record
      public.petstore_pets-values:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        schema:
          type: array
          items:
            fields:
              - name: id
                type:
                  - 'null'
                  - type: string
              - name: breed
                type:
                  - 'null'
                  - type: string
            name: petstore_pets
            namespace: public
            type: record
  messages:
    PETSTORE_PETSMessage:
      payload:
        "$ref": "#/components/schemas/public.petstore_pets-value"
      contentType: application/avro
      name: PETSTORE_PETSMessage
    PETSTORE_PETSMessages:
      payload:
        "$ref": "#/components/schemas/public.petstore_pets-values"
      contentType: application/avro
      name: PETSTORE_PETSMessages
    PETSTORE_CUSTOMERSMessages:
      payload:
        "$ref": "#/components/schemas/public.petstore_customers-values"
      contentType: application/avro
      name: PETSTORE_CUSTOMERSMessages
    PETSTORE_CUSTOMERSMessage:
      payload:
        "$ref": "#/components/schemas/public.petstore_customers-value"
      contentType: application/avro
      name: PETSTORE_CUSTOMERSMessage
    PETSTORE_VERIFIED_CUSTOMERSMessages:
      payload:
        "$ref": "#/components/schemas/public.petstore_verified_customers-values"
      contentType: application/avro
      name: PETSTORE_VERIFIED_CUSTOMERSMessages
    PETSTORE_VERIFIED_CUSTOMERSMessage:
      payload:
        "$ref": "#/components/schemas/public.petstore_verified_customers-value"
      contentType: application/avro
